'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  English: {
    // Nav & Dashboard
    home: 'Home',
    discover: 'Discover',
    bookings: 'Bookings',
    favorites: 'Favorites',
    profile: 'Profile',
    customerDashboard: 'Customer Dashboard',
    customerControlPanel: 'Customer Control Panel',
    cancelEditing: 'Cancel Editing',
    editProfile: 'Edit Profile',
    editInfo: 'Edit Info',
    personalInfo: 'Personal Information',
    addresses: 'Addresses',
    security: 'Security',
    notifications: 'Notifications',
    preferences: 'Preferences',
    loyaltyPoints: 'Loyalty Points',
    profileStrength: 'Profile Strength',
    rating: 'Rating',
    bioAbout: 'Bio / About',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    memberSince: 'Member Since',
    notProvided: 'Not provided',
    quickActivityHub: 'Quick Activity Hub',
    savedItemsHistory: 'Shortcuts to your saved items & booking history',
    favoriteCafes: 'Favorite Cafes',
    cafesBookmarked: 'cafes bookmarked',
    myBookings: 'My Bookings',
    totalBookings: 'total bookings',
    savedAddresses: 'Saved Addresses',
    manageAddresses: 'Manage your delivery and booking locations',
    addAddress: 'Add Address',
    securityPassword: 'Security & Password',
    manageSecurity: 'Manage your account authentication and active sessions',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    notificationPreferences: 'Notification Preferences',
    appPreferences: 'App Preferences',
    appearanceTheme: 'Appearance Theme',
    displayLanguage: 'Display Language',
    preferredAmenities: 'Preferred Cafe Amenities',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    warmLight: 'Warm Light',
    darkMocha: 'Dark Mocha',
    system: 'System',
    
    // Discovery & Filters & Cards
    searchPlaceholder: 'Search by cafe name, event, or location...',
    search: 'Search',
    filters: 'Filters',
    clearAll: 'Clear All',
    availability: 'AVAILABILITY',
    openNow: 'OPEN NOW',
    availableToday: 'Available Today',
    category: 'CATEGORY',
    anyCategory: 'Any Category',
    distance: 'DISTANCE',
    upTo50km: 'Up to 50 km',
    capacity: 'CAPACITY',
    anyCapacity: 'Any Capacity',
    cafesFound: 'Cafes Found',
    discoveringCafes: 'Discovering Cafes...',
    sortBy: 'Sort by:',
    popularity: 'Popularity',
    ratingHighToLow: 'Rating: High to Low',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    viewDetails: 'View Details',
    bookNow: 'Book Now',
    exploreCafes: 'Explore Cafes',
    nearbyCafes: 'Nearby Cafes',
    popularEvents: 'Popular Events & Offers',
    reviews: 'REVIEWS',
    pricePerHr: '₹/hr',
    noCafesFound: 'No cafes found',
    tryAdjustingFilters: 'Try adjusting your search filters or clear them to see all cafes.',
    heroTitle: 'Book Your Ideal Cafe & Event Experience',
    heroSubtitle: 'Discover top-rated cafes, reserve co-working spaces and plan memorable events effortlessly.',
    copyright: '© 2026 Fahara Inc. All rights reserved.',
  },
  Hindi: {
    home: 'होम',
    discover: 'खोजें',
    bookings: 'बुकिंग्स',
    favorites: 'पसंदीदा',
    profile: 'प्रोफ़ाइल',
    customerDashboard: 'ग्राहक डैशबोर्ड',
    customerControlPanel: 'ग्राहक नियंत्रण पैनल',
    cancelEditing: 'संपादन रद्द करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    editInfo: 'जानकारी बदलें',
    personalInfo: 'व्यक्तिगत जानकारी',
    addresses: 'पते',
    security: 'सुरक्षा',
    notifications: 'सूचनाएं',
    preferences: 'प्राथमिकताएं',
    loyaltyPoints: 'रिवॉर्ड पॉइंट्स',
    profileStrength: 'प्रोफ़ाइल पूर्णता',
    rating: 'रेटिंग',
    bioAbout: 'बायो / मेरे बारे में',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phoneNumber: 'फ़ोन नंबर',
    dateOfBirth: 'जन्म तिथि',
    gender: 'लिंग',
    memberSince: 'सदस्यता तिथि',
    notProvided: 'उपलब्ध नहीं',
    quickActivityHub: 'त्वरित गतिविधि हब',
    savedItemsHistory: 'आपके सहेजे गए स्थान और बुकिंग इतिहास',
    favoriteCafes: 'पसंदीदा कैफे',
    cafesBookmarked: 'सहेजे गए कैफे',
    myBookings: 'मेरी बुकिंग्स',
    totalBookings: 'कुल बुकिंग्स',
    savedAddresses: 'सहेजे गए पते',
    manageAddresses: 'अपने वितरण और बुकिंग स्थानों का प्रबंधन करें',
    addAddress: 'नया पता जोड़ें',
    securityPassword: 'सुरक्षा और पासवर्ड',
    manageSecurity: 'खाता प्रमाणीकरण प्रबंधित करें',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अद्यतन करें',
    notificationPreferences: 'सूचना प्राथमिकतियां',
    appPreferences: 'ऐप प्राथमिकतियां',
    appearanceTheme: 'थीम दिखावट',
    displayLanguage: 'प्रदर्शित भाषा',
    preferredAmenities: 'पसंदीदा कैफे सुविधाएं',
    saveChanges: 'सहेजें',
    cancel: 'रद्द करें',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    warmLight: 'वार्न लाइट',
    darkMocha: 'डार्क मोचा',
    system: 'सिस्टम',

    searchPlaceholder: 'कैफे नाम, कार्यक्रम या स्थान से खोजें...',
    search: 'खोजें',
    filters: 'फ़िल्टर',
    clearAll: 'सभी हटाएं',
    availability: 'उपलब्धता',
    openNow: 'अभी खुला है',
    availableToday: 'आज उपलब्ध है',
    category: 'श्रेणी',
    anyCategory: 'सभी श्रेणियां',
    distance: 'दूरी',
    upTo50km: '50 किमी तक',
    capacity: 'क्षमता',
    anyCapacity: 'कोई भी क्षमता',
    cafesFound: 'कैफे मिले',
    discoveringCafes: 'कैफे खोजे जा रहे हैं...',
    sortBy: 'क्रमानुसार:',
    popularity: 'लोकप्रियता',
    ratingHighToLow: 'रेटिंग: उच्च से निम्न',
    priceLowToHigh: 'मूल्य: कम से अधिक',
    priceHighToLow: 'मूल्य: अधिक से कम',
    viewDetails: 'विवरण देखें',
    bookNow: 'अभी बुक करें',
    exploreCafes: 'कैफे देखें',
    nearbyCafes: 'पास के कैफे',
    popularEvents: 'लोकप्रिय कार्यक्रम और ऑफ़र',
    reviews: 'समीक्षाएं',
    pricePerHr: '₹/घंटे',
    noCafesFound: 'कोई कैफे नहीं मिला',
    tryAdjustingFilters: 'अपने खोज फ़िल्टर समायोजित करने या उन्हें साफ़ करने का प्रयास करें।',
    heroTitle: 'अपना आदर्श कैफे और इवेंट अनुभव बुक करें',
    heroSubtitle: 'शीर्ष रेटेड कैफे खोजें, को-वर्किंग स्पेस आरक्षित करें और आसानी से योजना बनाएं।',
    copyright: '© 2026 फाहारा इंक. सर्वाधिकार सुरक्षित।',
  },
  Tamil: {
    home: 'முகப்பு',
    discover: 'கண்டறியவும்',
    bookings: 'முன்பதிவுகள்',
    favorites: 'விருப்பமானவை',
    profile: 'சுயவிவரம்',
    customerDashboard: 'வாடிக்கையாளர் பலகை',
    customerControlPanel: 'வாடிக்கையாளர் கட்டுப்பாட்டு பலகை',
    cancelEditing: 'ரத்து செய்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    editInfo: 'தகவலை திருத்து',
    personalInfo: 'தனிப்பட்ட தகவல்கள்',
    addresses: 'முகவரிகள்',
    security: 'பாதுகாப்பு',
    notifications: 'அறிவிப்புகள்',
    preferences: 'விருப்பத்தேர்வுகள்',
    loyaltyPoints: 'நன்மதிப்பு புள்ளிகள்',
    profileStrength: 'சுயவிவர நிறைவு',
    rating: 'மதிப்பீடு',
    bioAbout: 'சுயவிவரக் குறிப்பு',
    fullName: 'முழு பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    phoneNumber: 'தொலைபேசி எண்',
    dateOfBirth: 'பிறந்த தேதி',
    gender: 'பாலினம்',
    memberSince: 'உறுப்பினர் காலம்',
    notProvided: 'வழங்கப்படவில்லை',
    quickActivityHub: 'விரைவு செயல்பாட்டு மையம்',
    savedItemsHistory: 'சேமிக்கப்பட்ட கஃபேக்கள் மற்றும் முன்பதிவு வரலாறு',
    favoriteCafes: 'விருப்பமான கஃபேக்கள்',
    cafesBookmarked: 'சேமிக்கப்பட்ட கஃபேக்கள்',
    myBookings: 'எனது முன்பதிவுகள்',
    totalBookings: 'மொத்த முன்பதிவுகள்',
    savedAddresses: 'சேமிக்கப்பட்ட முகவரிகள்',
    manageAddresses: 'உங்கள் முகவரிகளை நிர்வகிக்கவும்',
    addAddress: 'புதிய முகவரி சேர்',
    securityPassword: 'பாதுகாப்பு மற்றும் கடவுச்சொல்',
    manageSecurity: 'கணக்கு பாதுகாப்பை நிர்வகிக்கவும்',
    currentPassword: 'தற்போதைய கடவுச்சொல்',
    newPassword: 'புதிய கடவுச்சொல்',
    confirmNewPassword: 'புதிய கடவுச்சொல்லை உறுதிசெய்',
    updatePassword: 'கடவுச்சொல்லை புதுப்பி',
    notificationPreferences: 'அறிவிப்பு விருப்பத்தேர்வுகள்',
    appPreferences: 'செயலி விருப்பத்தேர்வுகள்',
    appearanceTheme: 'தோற்ற கருப்பொருள்',
    displayLanguage: 'காட்சி மொழி',
    preferredAmenities: 'விருப்பமான வசதிகள்',
    saveChanges: 'சேமிக்கவும்',
    cancel: 'ரத்து செய்',
    male: 'ஆண்',
    female: 'பெண்',
    other: 'மற்றவை',
    warmLight: 'ஒளி தீம்',
    darkMocha: 'டார்க் மோகா',
    system: 'கணினி அமைவு',

    searchPlaceholder: 'கஃபே பெயர், நிகழ்வு அல்லது இடம் மூலம் தேடுங்கள்...',
    search: 'தேடு',
    filters: 'வடிகட்டிகள்',
    clearAll: 'அனைத்தையும் நீக்கு',
    availability: 'இருப்பு',
    openNow: 'திறந்துள்ளது',
    availableToday: 'இன்று கிடைக்கும்',
    category: 'வகை',
    anyCategory: 'அனைத்து வகைகளும்',
    distance: 'தூரம்',
    upTo50km: '50 கி.மீ வரை',
    capacity: 'கொள்திறன்',
    anyCapacity: 'அனைத்து கொள்ளளவும்',
    cafesFound: 'கஃபேக்கள் கண்டறியப்பட்டன',
    discoveringCafes: 'கஃபேக்கள் தேடப்படுகின்றன...',
    sortBy: 'வரிசைப்படுத்து:',
    popularity: 'பிரபலம்',
    ratingHighToLow: 'மதிப்பீடு: உயர் முதல் தாழ் வரை',
    priceLowToHigh: 'விலை: குறைந்ததிலிருந்து அதிகம்',
    priceHighToLow: 'விலை: அதிகத்திலிருந்து குறைந்த',
    viewDetails: 'விவரங்களை பார்க்க',
    bookNow: 'இப்போதே முன்பதிவு செய்க',
    exploreCafes: 'கஃபேக்களை ஆராயுங்கள்',
    nearbyCafes: 'அருகிலுள்ள கஃபேக்கள்',
    popularEvents: 'பிரபலமான நிகழ்வுகள் மற்றும் சலுகைகள்',
    reviews: 'மதிப்புரைகள்',
    pricePerHr: '₹/மணி',
    noCafesFound: 'கஃபேக்கள் எதுவும் கிடைக்கவில்லை',
    tryAdjustingFilters: 'உங்கள் தேடல் வடிகட்டிகளை மாற்ற முயற்சிக்கவும்.',
    heroTitle: 'உங்கள் சிறந்த கஃபே மற்றும் நிகழ்வு அனுபவத்தைப் பதிவுசெய்யவும்',
    heroSubtitle: 'சிறந்த கஃபேக்களைக் கண்டறியவும், பணிக்கான இடத்தை முன்பதிவு செய்யவும் எளிதாக திட்டமிடவும்.',
    copyright: '© 2026 ஃபஹாரா நிறுவனம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  },
  Spanish: {
    home: 'Inicio',
    discover: 'Descubrir',
    bookings: 'Reservas',
    favorites: 'Favoritos',
    profile: 'Perfil',
    customerDashboard: 'Panel de Cliente',
    customerControlPanel: 'Panel de Control de Cliente',
    cancelEditing: 'Cancelar Edición',
    editProfile: 'Editar Perfil',
    editInfo: 'Editar Info',
    personalInfo: 'Información Personal',
    addresses: 'Direcciones',
    security: 'Seguridad',
    notifications: 'Notificaciones',
    preferences: 'Preferencias',
    loyaltyPoints: 'Puntos de Fidelidad',
    profileStrength: 'Nivel de Perfil',
    rating: 'Calificación',
    bioAbout: 'Biografía / Acerca de mí',
    fullName: 'Nombre Completo',
    emailAddress: 'Correo Electrónico',
    phoneNumber: 'Número de Teléfono',
    dateOfBirth: 'Fecha de Nacimiento',
    gender: 'Género',
    memberSince: 'Miembro Desde',
    notProvided: 'No proporcionado',
    quickActivityHub: 'Centro de Actividad Rápida',
    savedItemsHistory: 'Accesos directos a tus elementos guardados e historial',
    favoriteCafes: 'Cafeterías Favoritas',
    cafesBookmarked: 'cafeterías guardadas',
    myBookings: 'Mis Reservas',
    totalBookings: 'reservas totales',
    savedAddresses: 'Direcciones Guardadas',
    manageAddresses: 'Gestiona tus direcciones de entrega y reserva',
    addAddress: 'Agregar Dirección',
    securityPassword: 'Seguridad y Contraseña',
    manageSecurity: 'Gestiona la autenticación de tu cuenta',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmNewPassword: 'Confirmar Nueva Contraseña',
    updatePassword: 'Actualizar Contraseña',
    notificationPreferences: 'Preferencias de Notificación',
    appPreferences: 'Preferencias de Aplicación',
    appearanceTheme: 'Tema de Apariencia',
    displayLanguage: 'Idioma de Pantalla',
    preferredAmenities: 'Servicios Preferidos',
    saveChanges: 'Guardar Cambios',
    cancel: 'Cancelar',
    male: 'Masculino',
    female: 'Femenino',
    other: 'Otro',
    warmLight: 'Luz Cálida',
    darkMocha: 'Moca Oscuro',
    system: 'Sistema',

    searchPlaceholder: 'Buscar por nombre de cafetería, evento o ubicación...',
    search: 'Buscar',
    filters: 'Filtros',
    clearAll: 'Borrar Todo',
    availability: 'DISPONIBILIDAD',
    openNow: 'ABIERTO AHORA',
    availableToday: 'Disponible Hoy',
    category: 'CATEGORÍA',
    anyCategory: 'Cualquier Categoría',
    distance: 'DISTANCIA',
    upTo50km: 'Hasta 50 km',
    capacity: 'CAPACIDAD',
    anyCapacity: 'Cualquier Capacidad',
    cafesFound: 'Cafeterías Encontradas',
    discoveringCafes: 'Buscando cafeterías...',
    sortBy: 'Ordenar por:',
    popularity: 'Popularidad',
    ratingHighToLow: 'Calificación: Alta a Baja',
    priceLowToHigh: 'Precio: Menor a Mayor',
    priceHighToLow: 'Precio: Mayor a Menor',
    viewDetails: 'Ver Detalles',
    bookNow: 'Reservar Ahora',
    exploreCafes: 'Explorar Cafeterías',
    nearbyCafes: 'Cafeterías Cercanas',
    popularEvents: 'Eventos y Ofertas Populares',
    reviews: 'RESEÑAS',
    pricePerHr: '₹/hr',
    noCafesFound: 'No se encontraron cafeterías',
    tryAdjustingFilters: 'Intenta ajustar tus filtros de búsqueda.',
    heroTitle: 'Reserva tu Experiencia Ideal en Cafeterías y Eventos',
    heroSubtitle: 'Descubre las mejores cafeterías, reserva espacios de trabajo y planifica eventos sin esfuerzo.',
    copyright: '© 2026 Fahara Inc. Todos los derechos reservados.',
  },
  French: {
    home: 'Accueil',
    discover: 'Découvrir',
    bookings: 'Réservations',
    favorites: 'Favoris',
    profile: 'Profil',
    customerDashboard: 'Tableau de Bord Client',
    customerControlPanel: 'Panneau de Contrôle Client',
    cancelEditing: 'Annuler',
    editProfile: 'Modifier le Profil',
    editInfo: 'Modifier les Infos',
    personalInfo: 'Informations Personnelles',
    addresses: 'Adresses',
    security: 'Sécurité',
    notifications: 'Notifications',
    preferences: 'Préférences',
    loyaltyPoints: 'Points de Fidélité',
    profileStrength: 'Niveau du Profil',
    rating: 'Évaluation',
    bioAbout: 'Biographie / À propos',
    fullName: 'Nom Complet',
    emailAddress: 'Adresse Email',
    phoneNumber: 'Numéro de Téléphone',
    dateOfBirth: 'Date de Naissance',
    gender: 'Genre',
    memberSince: 'Membre Depuis',
    notProvided: 'Non fourni',
    quickActivityHub: 'Centre d\'Activité Rapide',
    savedItemsHistory: 'Raccourcis vers vos favoris et historique',
    favoriteCafes: 'Cafés Favoris',
    cafesBookmarked: 'cafés enregistrés',
    myBookings: 'Mes Réservations',
    totalBookings: 'réservations totales',
    savedAddresses: 'Adresses Enregistrées',
    manageAddresses: 'Gérez vos adresses de livraison et réservation',
    addAddress: 'Ajouter une Adresse',
    securityPassword: 'Sécurité et Mot de Passe',
    manageSecurity: 'Gérez l\'authentification de votre compte',
    currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe',
    confirmNewPassword: 'Confirmer le Nouveau Mot de Passe',
    updatePassword: 'Mettre à Jour le Mot de Passe',
    notificationPreferences: 'Préférences de Notification',
    appPreferences: 'Préférences de l\'Application',
    appearanceTheme: 'Thème d\'Apparence',
    displayLanguage: 'Langue d\'Affichage',
    preferredAmenities: 'Équipements Préférés',
    saveChanges: 'Enregistrer les Modifications',
    cancel: 'Annuler',
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',
    warmLight: 'Lumière Chaude',
    darkMocha: 'Mocha Sombre',
    system: 'Système',

    searchPlaceholder: 'Rechercher par nom de café, événement ou lieu...',
    search: 'Rechercher',
    filters: 'Filtres',
    clearAll: 'Tout Effacer',
    availability: 'DISPONIBILITÉ',
    openNow: 'OUVERT',
    availableToday: 'Disponible Aujourd\'hui',
    category: 'CATÉGORIE',
    anyCategory: 'Toute Catégorie',
    distance: 'DISTANCE',
    upTo50km: 'Jusqu\'à 50 km',
    capacity: 'CAPACITÉ',
    anyCapacity: 'Toute Capacité',
    cafesFound: 'Cafés Trouvés',
    discoveringCafes: 'Recherche de cafés...',
    sortBy: 'Trier par:',
    popularity: 'Popularité',
    ratingHighToLow: 'Note: Élevée à Basse',
    priceLowToHigh: 'Prix: Bas à Élevé',
    priceHighToLow: 'Prix: Élevé à Bas',
    viewDetails: 'Voir les Détails',
    bookNow: 'Réserver Maintenant',
    exploreCafes: 'Explorer les Cafés',
    nearbyCafes: 'Cafés à Proximité',
    popularEvents: 'Événements et Offres Populaires',
    reviews: 'AVIS',
    pricePerHr: '₹/hr',
    noCafesFound: 'Aucun café trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster vos filtres de recherche.',
    heroTitle: 'Réservez Votre Expérience Café & Événement Idéale',
    heroSubtitle: 'Découvrez les meilleurs cafés, réservez des espaces de travail et planifiez des événements sans effort.',
    copyright: '© 2026 Fahara Inc. Tous droits réservés.',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('English');

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem('fahara-language');
      if (savedLang && translations[savedLang]) {
        setLanguageState(savedLang);
      }
    } catch (e) {
      console.error('Error reading language', e);
    }
  }, []);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('fahara-language', lang);
      if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
      }
    }
  };

  const t = (key, fallback = '') => {
    const langDict = translations[language] || translations.English;
    return langDict[key] || fallback || translations.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'English',
      setLanguage: () => {},
      t: (key, fallback = '') => fallback || key,
    };
  }
  return context;
}
